import { renderCircuitSvg } from '@qcc/core';
import { Download } from 'lucide-react';
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { useStore } from '../store';

const PNG_SCALE = 3;

function save(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  Object.assign(document.createElement('a'), { href: url, download: filename }).click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Rasterizes the SVG at a print-friendly scale. */
function savePng(svg: string) {
  const url = URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' }));
  const img = new Image();
  img.onload = () => {
    const canvas = document.createElement('canvas');
    canvas.width = img.width * PNG_SCALE;
    canvas.height = img.height * PNG_SCALE;
    const ctx = canvas.getContext('2d')!;
    ctx.scale(PNG_SCALE, PNG_SCALE);
    ctx.drawImage(img, 0, 0);
    URL.revokeObjectURL(url);
    canvas.toBlob((blob) => blob && save(blob, 'circuit.png'), 'image/png');
  };
  img.src = url;
}

/**
 * A figure of the circuit in the style of the quantikz output, so the LaTeX
 * result can be checked without compiling it. Also exports SVG and PNG.
 */
export default function CircuitPreview() {
  const { t } = useTranslation();
  const circuit = useStore((s) => s.circuit);
  const svg = useMemo(() => renderCircuitSvg(circuit), [circuit]);
  const btn = 'flex items-center gap-1 rounded-md border border-line-strong px-2 py-1 text-xs hover:bg-surface-2';

  return (
    <figure className="space-y-2">
      <div className="flex items-center justify-between gap-2">
        <figcaption className="text-xs text-muted">{t('output.preview')}</figcaption>
        <div className="flex gap-1.5">
          <button type="button" className={btn} onClick={() => save(new Blob([svg], { type: 'image/svg+xml' }), 'circuit.svg')}>
            <Download size={14} />
            SVG
          </button>
          <button type="button" className={btn} onClick={() => savePng(svg)}>
            <Download size={14} />
            PNG
          </button>
        </div>
      </div>
      {/* The SVG is generated by renderCircuitSvg, which escapes all user text. */}
      <div
        className="overflow-x-auto rounded-lg border border-line bg-white p-2 [&>svg]:max-w-none"
        role="img"
        aria-label={t('output.preview')}
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </figure>
  );
}
